spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/persistencia
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "format_sql": true

  data:
    mongodb:
      uri: mongodb://localhost:27017/persistencia

server:
  port: 8080
